### PR TITLE
add codable reflection

### PR DESCRIPTION
**Pull request by tanner0101**
Adds Swift type reflection protocols and types alongside a default Codable-based implementation. This code makes up for lacking type-reflection in Swift and the inability to get string values for key paths. Hopefully this code will be rendered obsolete by improved reflection in a future version of Swift, but this is unlikely to land until at least Swift 6.

Reflection is based around a type `ReflectedProperty`.

```swift
public struct ReflectedProperty {
    /// This property's type.
    public let type: Any.Type
    
    /// The path to this property.
    public let path: [String]
}
```

Reflection is exposed on conformers to `Reflectable` via two static methods:

```swift
func reflectProperties(depth: Int) throws -> [ReflectedProperty]
func reflectProperty<T>(forKey keyPath: WritableKeyPath<Self, T>) throws -> ReflectedProperty?
```

Reflecting properties returns an array of all properties on the type. This is limited by a supplied depth parameter, that defaults to 1, since some types may be recursive.

Reflecting a single property allows you to convert a KeyPath to a reflected property.

Take the following example:

```swift
struct Planet: Reflectable, Codable {
    var id: UUID?
    var name: String
}

let properties = try Planet.reflectProperties()
print(properties) // [id: UUID?, name: String]

let id = try Planet.reflectProperty(forKey: \.id)
print(id!) // [path: "id", type: UUID?]
let name = try Planet.reflectProperty(forKey: \.name)
print(name!) // [path: "name", type: String]
```

### CODE REVIEW

**Comment by twof** [comment]
in the case of
```swift
let name = try Planet.reflectProperty(forKey: \.name)
print(name!) // [path: "name", type: String]
```
What would a more deeply nested keypath look like? For example
```swift
let name = try Planet.reflectProperty(forKey: \.name.count)
print(name!) // [path: "name", type: String]
```

**Comment by tanner0101** [comment]
@twof `path` is an array (not super clear from my comments, sorry). For that example, it would be `["name", "count"]`. However, that wouldn't work because `count` is a computed property and this only works for stored (Codable) properties. As written, that wouldn't compile because the method requires a `WritableKeyPath`. It _would_ work with a property in a nested struct though. There's actually a test case for that in this PR. That's important for enabling features like filtering JSON columns in Fluent going forward :)

**Comment by tanner0101** [comment]
Bump on this one. After #6, we should merge it through.

**Review by calebkleveter — APPROVED** [review]

**Comment by penny-coin** [comment]
Hey @tanner0101, you just merged a pull request, have a coin! 

You now have 1036 coins.

**Pull request merged**
